CoD.QRDrone = {}
LUI.createMenu.qrdrone_mp = function (f1_arg0)
	local f1_local0 = CoD.AirVehicleHUD.new("qrdrone_mp", f1_arg0, nil, nil, nil, "digital_noise_filter_qrdrone")
	f1_local0:addCompass()
	local f1_local1 = RegisterMaterial("mp_hud_scorestreak_bracket")
	local f1_local2 = 64
	local f1_local3 = 512
	local f1_local4 = 400
	local f1_local5 = LUI.UIImage.new()
	f1_local5:setLeftRight(false, false, -f1_local4, -f1_local4 + f1_local2)
	f1_local5:setTopBottom(false, false, -f1_local3 / 2, f1_local3 / 2)
	f1_local5:setImage(f1_local1)
	f1_local5:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
	f1_local0:addElement(f1_local5)
	local f1_local6 = LUI.UIImage.new()
	f1_local6:setLeftRight(false, false, f1_local4, f1_local4 - f1_local2)
	f1_local6:setTopBottom(false, false, -f1_local3 / 2, f1_local3 / 2)
	f1_local6:setImage(f1_local1)
	f1_local6:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
	f1_local0:addElement(f1_local6)
	local f1_local7 = LUI.UIImage.new()
	f1_local7:setupRollLevel(1)
	f1_local7:setLeftRight(false, false, -256, 256)
	f1_local7:setTopBottom(false, false, -128, 128)
	f1_local7:setImage(RegisterMaterial("mp_hud_wasp_inner_white"))
	f1_local7:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
	f1_local0:addElement(f1_local7)
	local f1_local8 = LUI.UIImage.new()
	f1_local8:setupRollLevel(-1)
	f1_local8:setLeftRight(false, false, -256, 256)
	f1_local8:setTopBottom(false, false, -256, 256)
	f1_local8:setImage(RegisterMaterial("mp_hud_wasp_outer_white"))
	f1_local8:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
	f1_local0:addElement(f1_local8)
	local f1_local9 = LUI.UIImage.new()
	f1_local9:setLeftRight(false, false, -32, 32)
	f1_local9:setTopBottom(false, false, -32, 32)
	f1_local9:setImage(RegisterMaterial("mp_hud_wasp_crosshair_white"))
	f1_local9:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
	f1_local0:addElement(f1_local9)
	local f1_local10 = CoD.SplitscreenScaler.new(nil, CoD.SplitscreenMultiplier)
	f1_local10:setLeftRight(false, true, 0, 0)
	f1_local10:setTopBottom(false, true, 0, 0)
	f1_local0.safeAreaContainer:addElement(f1_local10)
	local Widget = LUI.UIElement.new()
	Widget:setLeftRight(false, true, -100, 0)
	Widget:setTopBottom(false, true, -CoD.textSize.Condensed - 4 - CoD.AirVehicleHUD.BottomBarHeight, -CoD.AirVehicleHUD.BottomBarHeight)
	f1_local10:addElement(Widget)
	Widget:addElement(CoD.Border.new(2, CoD.AirVehicleHUD.HUDColor.r, CoD.AirVehicleHUD.HUDColor.g, CoD.AirVehicleHUD.HUDColor.b, CoD.AirVehicleHUD.Alpha))
	local f1_local12 = LUI.UIText.new()
	f1_local12:setLeftRight(true, false, -40, 0)
	f1_local12:setTopBottom(false, false, -CoD.textSize.Condensed / 2, CoD.textSize.Condensed / 2)
	f1_local12:setRGB(CoD.AirVehicleHUD.HUDColor.r, CoD.AirVehicleHUD.HUDColor.g, CoD.AirVehicleHUD.HUDColor.b)
	f1_local12:setAlpha(CoD.AirVehicleHUD.Alpha)
	f1_local12:setFont(CoD.fonts.Condensed)
	f1_local12:setText("REC")
	Widget:addElement(f1_local12)
	local f1_local13 = LUI.UIText.new()
	f1_local13:setLeftRight(true, false, 13, 14)
	f1_local13:setTopBottom(false, false, -CoD.textSize.Condensed / 2, CoD.textSize.Condensed / 2)
	f1_local13:setRGB(CoD.AirVehicleHUD.HUDColor.r, CoD.AirVehicleHUD.HUDColor.g, CoD.AirVehicleHUD.HUDColor.b)
	f1_local13:setFont(CoD.fonts.Condensed)
	f1_local13:setAlpha(CoD.AirVehicleHUD.Alpha)
	f1_local13:setUseGameTime(true)
	f1_local13:setText("00:00.00")
	f1_local13.milliseconds = 0
	f1_local13.seconds = 0
	f1_local13:registerEventHandler("countup_tick", CoD.AirVehicleHUD.RecordingTimerTick)
	Widget:addElement(f1_local13)
	Widget:addElement(LUI.UITimer.new(10, "countup_tick", false, f1_local13))
	if CoD.IS_KILLCAM_OR_SPECTATE(f1_arg0) == 0 and UIExpression.IsDemoPlaying(f1_arg0) == 0 then
		local f1_local14 = LUI.UIText.new()
		f1_local14:setLeftRight(true, false, 0, 0)
		f1_local14:setTopBottom(false, true, -CoD.textSize.Default, 0)
		f1_local14:setText(Engine.Localize("MP_QRDRONE_DESCEND"))
		f1_local14:setFont(CoD.fonts.Default)
		f1_local14:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
		f1_local0.leftButtonPrompts:addElement(f1_local14)
		local f1_local15 = LUI.UIText.new()
		f1_local15:setLeftRight(true, false, 0, 0)
		f1_local15:setTopBottom(false, true, -30 - CoD.textSize.Default, -30)
		f1_local15:setText(Engine.Localize("MP_REMOTE_EXIT"))
		f1_local15:setFont(CoD.fonts.Default)
		f1_local15:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
		f1_local0.leftButtonPrompts:addElement(f1_local15)
		local f1_local16 = LUI.UIText.new()
		f1_local16:setLeftRight(false, true, -1000, 0)
		f1_local16:setTopBottom(false, true, -CoD.textSize.Default, 0)
		f1_local16:setText(Engine.Localize("MP_QRDRONE_ASCEND"))
		f1_local16:setFont(CoD.fonts.Default)
		f1_local16:setAlignment(LUI.Alignment.Right)
		f1_local16:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
		f1_local0.rightButtonPrompts:addElement(f1_local16)
		local f1_local17 = LUI.UIText.new()
		f1_local17:setLeftRight(false, true, -1000, 0)
		f1_local17:setTopBottom(false, true, -30 - CoD.textSize.Default, -30)
		f1_local17:setText(Engine.Localize("MP_QRDRONE_ATTACK"))
		f1_local17:setFont(CoD.fonts.Default)
		f1_local17:setAlignment(LUI.Alignment.Right)
		f1_local17:setRGB(f1_local0.colorR, f1_local0.colorG, f1_local0.colorB)
		f1_local0.rightButtonPrompts:addElement(f1_local17)
	end
	return f1_local0
end

